#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug  3 09:36:58 2019

@author: aneekalatif
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 14 09:23:12 2019

@author: aneekalatif
"""

from matplotlib import pyplot as plt
import nltk
import string
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.probability import FreqDist
from nltk.stem.porter import PorterStemmer 
from wordcloud import WordCloud
import csv
import re
from collections import Counter, defaultdict 





#starting the tokenization of text into words
#Read in text 

#read the csv as a dataframe 
review = pd.read_csv('data/yelpreviewsample100.csv')
#get the first 25 reviews 
#manually saved to a file and columns removed in excel
#check the first 25 
review = review[0:25]


#import the annotated data 
annot = pd.read_csv('data/yelpsampleannotated.csv')

#make arrays for each of the raters

#split the ratings by rater 
rater1=annot[0::5]
rater2=annot[1::5]
rater3=annot[2::5]
rater4=annot[3::5]
rater5=annot[4::5]

#isolate the annotations only
rater1an=rater1['Answer.sentiment.label']
rater2an=rater2['Answer.sentiment.label']
rater3an=rater3['Answer.sentiment.label']
rater4an=rater4['Answer.sentiment.label']
rater5an=rater5['Answer.sentiment.label']


#calculate pairwise kappa scores
from sklearn.metrics import cohen_kappa_score

cohen_kappa_score(rater1an, rater2an)
cohen_kappa_score(rater1an, rater3an)
cohen_kappa_score(rater1an, rater4an)
cohen_kappa_score(rater1an, rater5an)

cohen_kappa_score(rater2an, rater3an)
cohen_kappa_score(rater2an, rater4an)
cohen_kappa_score(rater2an, rater5an)

cohen_kappa_score(rater3an, rater4an)
cohen_kappa_score(rater3an, rater5an)

cohen_kappa_score(rater4an, rater5an)

(0.38202247191011229+0.17035398230088483+0.064449064449064508+
0.4600431965442765+0.31434599156118148+
0.28425357873210644)/7

